In [1]:
import numpy as np

In [4]:
# 배열 생성
# 1차원
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1)) # nd=차원
print(a1.shape) # 3,  1차원 // 원소개수와 차원
print(a1[0], a1[2])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 3
[4 5 6 4 5]


In [7]:
#2차원
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(a2.shape) # 3,3 2차원
print(a2[0,0], a2[1,1],a2[2,2]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [8]:
#3차원
a3 = np.array([ [[1,2,3], [4,5,6], [7,8,9]],
                [[1,2,3], [4,5,6], [7,8,9]],
                [[1,2,3], [4,5,6], [7,8,9]] ])
print(a3)
print(a3.shape) #3,3,3 3차원

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


In [10]:
np.zeros(10) # 10개의 요소를 모두 0으로 초기화 된 배열로 만들어줘

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10) # 1로 채워줘

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((3,3)) # 2차원형태의 1로 채워줘

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [14]:
np.eye(3) #단일행렬 생성 : 정사각행렬 / 특징 : 주대각 원소가 모드 1이고, 나머지 원소는 모두 0인 정사각행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [17]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [20]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [22]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
np.linspace(0, 1, 5) #0부터 1까지 5구간으로 균등하게 나눠줘

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])